<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ModelContextProtocol.AspNetCore" Version="2.2.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ManiaScriptSharp\ManiaScriptSharp.csproj" />
        <ProjectReference Include="..\ManiaScriptSharp.ManiaPlanet\ManiaScriptSharp.ManiaPlanet.csproj" />
        <ProjectReference Include="..\ManiaScriptSharp.ManiaPlanet3\ManiaScriptSharp.ManiaPlanet3.csproj" />
        <ProjectReference Include="..\ManiaScriptSharp.Trackmania\ManiaScriptSharp.Trackmania.csproj" />
    </ItemGroup>

</Project>
