<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <Description>API surface for ManiaPlanet 3 ManiaScript classes.</Description>
        <RootNamespace>ManiaScriptSharp</RootNamespace>
        <NoWarn>$(NoWarn);CS1591;CS0108;CS0114;CS0436;CS0109</NoWarn>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <!-- Exclude the output of source generators from the compilation -->
        <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ManiaScriptSharp\ManiaScriptSharp.csproj" />
        <ProjectReference Include="..\ManiaScriptSharp.ApiGenerator\ManiaScriptSharp.ApiGenerator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="doc.h" />
        <AdditionalFiles Include="Scripts/**/*.Script.txt" />
    </ItemGroup>

    <ItemGroup>
        <CompilerVisibleProperty Include="ManiaScriptApiNamespaceLibsStatic" />
        <CompilerVisibleProperty Include="ManiaScriptApiStandardizeParamNames" />
    </ItemGroup>

</Project>
