<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>ManiaScriptSharp.ManiaPlanet3</PackageId>
        <VersionPrefix>1.0.0</VersionPrefix>
        <VersionSuffix>alpha.1</VersionSuffix>
        <Authors>BigBang1112</Authors>
        <Description>API surface for ManiaPlanet 3 ManiaScript classes.</Description>
        <Copyright>Copyright (c) 2026 Petr Pivoňka</Copyright>
        <PackageProjectUrl>https://github.com/BigBang1112/maniascript-sharp</PackageProjectUrl>
        <PackageTags>maniascript;api;trackmania;maniaplanet</PackageTags>
        <PackageReleaseNotes></PackageReleaseNotes>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFrameworks>net10.0;net8.0;netstandard2.0</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <RootNamespace>ManiaScriptSharp</RootNamespace>
        <NoWarn>$(NoWarn);CS1591;CS0108;CS0114;CS0436;CS0109</NoWarn>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <!-- Exclude the output of source generators from the compilation -->
        <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ManiaScriptSharp\ManiaScriptSharp.csproj" />
        <ProjectReference Include="..\ManiaScriptSharp.ApiGenerator\ManiaScriptSharp.ApiGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="doc.h" />
        <AdditionalFiles Include="Scripts/**/*.Script.txt" />
    </ItemGroup>

    <ItemGroup>
        <CompilerVisibleProperty Include="ManiaScriptApiNamespaceLibsStatic" />
        <CompilerVisibleProperty Include="ManiaScriptApiStandardizeParamNames" />
    </ItemGroup>

</Project>
