using Xunit;

namespace ManiaScriptSharp.Generator.Tests;

public class ExpressionEmitterTests : EmitterTestBase
{
    // ────────── Boolean literals ──────────

    [Fact]
    public void Translate_TrueLiteral()
    {
        Assert.Equal("True", TranslateExpr("true"));
    }

    [Fact]
    public void Translate_FalseLiteral()
    {
        Assert.Equal("False", TranslateExpr("false"));
    }

    [Fact]
    public void Translate_NullLiteral()
    {
        Assert.Equal("Null", TranslateExpr("null"));
    }

    [Fact]
    public void Translate_NullForgivingOperator_InsertsComment()
    {
        Assert.Equal("G_Item/* not Null here */", TranslateExpr("item!", "string? item;"));
        Assert.Equal("Null/* not Null here */", TranslateExpr("null!"));
    }

    [Fact]
    public void Translate_NullForgivingOperator_BeforeMemberAccess()
    {
        Assert.Equal("G_Foo/* not Null here */.Bar",
            TranslateExpr("foo!.Bar", "class Foo { public int Bar; } Foo? foo;"));
    }

    [Fact]
    public void Translate_NullLiteral_ForIdentField_BecomesNullId()
    {
        Assert.Equal("G_X = NullId", TranslateExpr("x = null", "public struct Ident {} Ident? x;"));
    }

    [Fact]
    public void Translate_NullLiteral_ForNonIdentField_StaysNull()
    {
        Assert.Equal("G_X = Null", TranslateExpr("x = null", "public class Foo {} Foo? x;"));
    }

    [Fact]
    public void Translate_IdentNullId_StaticField_EmitsBareNullId()
    {
        Assert.Equal("NullId", TranslateExpr("Ident.NullId", "public struct Ident { public static readonly Ident NullId = default; }"));
    }

    [Fact]
    public void Translate_StringEmpty_EmitsEmptyStringLiteral()
    {
        Assert.Equal("\"\"", TranslateExpr("string.Empty"));
    }

    [Fact]
    public void Translate_StringEmpty_ReportsNoDiagnostics()
    {
        var (output, diagnostics) = TranslateExprWithDiagnostics("string.Empty");
        Assert.Equal("\"\"", output);
        Assert.Empty(diagnostics);
    }

    [Fact]
    public void Translate_AutoGeneratedApiPropertyAssign_StaysPlainFieldAssignment()
    {
        // CUILayer.IsVisible et al. are plain header-derived auto-properties (declared in a
        // .g.cs file, no user C# body) — they map to real ManiaScript fields, so assigning to
        // them must stay a plain `Obj.Field = value` and not become a `Obj::SetField(value)` call.
        var extra = "class CUILayer { public bool IsVisible { get; set; } } CUILayer layer = new CUILayer();";
        var output = TranslateExprFromGeneratedSource("layer.IsVisible = true", extra);
        Assert.Equal("G_Layer.IsVisible = True", output);
    }

    [Fact]
    public void Translate_HandAuthoredApiPropertyRead_StaysPlainFieldAccess()
    {
        // Some API types (e.g. CMlBrowser.CurMap) are patched with a hand-written partial-class
        // property in a plain (non-.g.cs) file rather than the generator, since they aren't
        // IContext/ILib types themselves — they must still stay plain field access, not a
        // GetXxx() call, even though the file-suffix check alone can't tell them apart from
        // real user-defined properties.
        var extra = "class CMlBrowser { public object CurMap { get; } } CMlBrowser browser = new CMlBrowser();";
        var output = TranslateExpr("browser.CurMap == null", extra);
        Assert.Equal("G_Browser.CurMap == Null", output);
    }

    [Fact]
    public void Translate_DefaultLiteral()
    {
        // default(T) is a DefaultExpressionSyntax — not explicitly handled,
        // so it falls through to the /* SyntaxKind */ comment.
        Assert.Equal("/* DefaultExpression */", TranslateExpr("default(int)"));
    }

    // ────────── Numeric literals ──────────

    [Theory]
    [InlineData("42", "42")]
    [InlineData("0", "0")]
    [InlineData("100", "100")]
    public void Translate_IntegerLiteral(string input, string expected)
    {
        Assert.Equal(expected, TranslateExpr(input));
    }

    [Fact]
    public void Translate_FloatWithDecimal_PreservesDecimal()
    {
        Assert.Equal("3.14", TranslateExpr("3.14f"));
    }

    [Fact]
    public void Translate_FloatSuffixStripped()
    {
        // 1.5f → suffix stripped → "1.5"
        Assert.Equal("1.5", TranslateExpr("1.5f"));
    }

    [Fact]
    public void Translate_FloatWholeNumber_AddsDecimalPoint()
    {
        // 2f → "2" + "." → "2."
        Assert.Equal("2.", TranslateExpr("2f"));
    }

    [Fact]
    public void Translate_DoubleSuffixStripped()
    {
        Assert.Equal("1.5", TranslateExpr("1.5d"));
    }

    [Fact]
    public void Translate_DoubleLiteralNoSuffix_WithDecimal()
    {
        Assert.Equal("3.14", TranslateExpr("3.14"));
    }

    // ────────── String literals ──────────

    [Fact]
    public void Translate_StringLiteral_PreservesQuotes()
    {
        Assert.Equal("\"hello\"", TranslateExpr("\"hello\""));
    }

    [Fact]
    public void Translate_VerbatimString_TripleQuoted()
    {
        Assert.Equal("\"\"\"foo\"\"\"", TranslateExpr("@\"foo\""));
    }

    [Fact]
    public void Translate_LongVerbatimString_SplitsMultilineStringFragmentsAtByteLimit()
    {
        var text = new string('x', 65_536);

        var output = TranslateExpr("@\"" + text + "\"");

        Assert.Equal("\"\"\"" + new string('x', 65_535) + "\"\"\" ^ \"\"\"x\"\"\"", output);
    }

    [Fact]
    public void Translate_MultibyteVerbatimString_SplitsByUtf8Bytes()
    {
        var text = new string('\u00E9', 32_768); // 65,536 UTF-8 bytes

        var output = TranslateExpr("@\"" + text + "\"");

        Assert.Equal("\"\"\"" + new string('\u00E9', 32_767) + "\"\"\" ^ \"\"\"\u00E9\"\"\"", output);
    }

    [Fact]
    public void Translate_VerbatimString_WithTripleQuotes_ComposesSafeFragments()
    {
        var output = TranslateExpr("@\"Before \"\"\"\"\"\" after\"");

        Assert.Equal("\"\"\"Before \"\"\" ^ \"\\\"\\\"\\\"\" ^ \"\"\" after\"\"\"", output);
    }

    [Fact]
    public void Translate_VerbatimString_WithInterpolationMarker_ComposesSafeFragments()
    {
        var output = TranslateExpr("@\"Before {{{ after\"");

        Assert.Equal("\"\"\"Before \"\"\" ^ \"{{{\" ^ \"\"\" after\"\"\"", output);
    }

    [Fact]
    public void Translate_CharLiteral_AsString()
    {
        Assert.Equal("\"A\"", TranslateExpr("'A'"));
    }

    // ────────── Unary operators ──────────

    [Fact]
    public void Translate_PrefixNegation_Preserved()
    {
        Assert.Equal("-5", TranslateExpr("-5"));
    }

    [Fact]
    public void Translate_PrefixNot_Preserved()
    {
        Assert.Equal("!True", TranslateExpr("!true"));
    }

    [Fact]
    public void Translate_PostfixIncrement_BecomesPlusEquals()
    {
        Assert.Equal("G_X += 1", TranslateExpr("x++", "int x;"));
    }

    [Fact]
    public void Translate_PostfixDecrement_BecomesMinusEquals()
    {
        Assert.Equal("G_X -= 1", TranslateExpr("x--", "int x;"));
    }

    // ────────── Binary operators ──────────

    [Theory]
    [InlineData("a + b", "a + b")]
    [InlineData("a - b", "a - b")]
    [InlineData("a * b", "a * b")]
    [InlineData("a / b", "a / b")]
    [InlineData("a % b", "a % b")]
    [InlineData("a == b", "a == b")]
    [InlineData("a != b", "a != b")]
    [InlineData("a < b", "a < b")]
    [InlineData("a > b", "a > b")]
    [InlineData("a <= b", "a <= b")]
    [InlineData("a >= b", "a >= b")]
    public void Translate_BinaryOperators_PreservedForNonString(string expr, string expected)
    {
        // These are unresolved identifiers; model returns null → raw identifier text
        Assert.Equal(expected, TranslateExpr(expr));
    }

    [Fact]
    public void Translate_StringConcatenation_UsesCaretOperator()
    {
        // With resolved string type, + must become ^
        Assert.Equal("\"a\" ^ \"b\"", TranslateExpr("\"a\" + \"b\""));
    }

    [Fact]
    public void Translate_StringPlusIdentifier_UsesCaretOperator()
    {
        Assert.Equal("\"prefix\" ^ G_S", TranslateExpr("\"prefix\" + s", "string s;"));
    }

    // ────────── Compound expressions ──────────

    [Fact]
    public void Translate_Parenthesized_WrapsInParens()
    {
        Assert.Equal("(1 + 2)", TranslateExpr("(1 + 2)"));
    }

    [Fact]
    public void Translate_CastExpression_AsForm()
    {
        // (int)x → cast emits as `(X as Integer)` because x is a private field (mangled to X)
        // and the target type is mapped through TypeMapper, not emitted verbatim.
        Assert.Equal("(G_X as Integer)", TranslateExpr("(int)x", "object x;"));
    }

     // ────────── Basic-type casts ──────────

    [Fact]
    public void Translate_Cast_IntToFloat_UsesMathLibToReal()
    {
        Assert.Equal("MathLib::ToReal(G_X)", TranslateExpr("(float)x", "int x;"));
    }

    [Fact]
    public void Translate_Cast_FloatToInt_UsesMathLibTruncInteger()
    {
        // Explicit cast truncates toward zero, matching C# semantics.
        Assert.Equal("MathLib::TruncInteger(G_X)", TranslateExpr("(int)x", "float x;"));
    }

    [Fact]
    public void Translate_Cast_LongToInt_IsNoOp()
    {
        // Both map to ManiaScript's single Integer type.
        Assert.Equal("G_X", TranslateExpr("(int)x", "long x;"));
    }

    [Fact]
    public void Translate_Cast_DoubleToFloat_IsNoOp()
    {
        // Both map to ManiaScript's single Real type.
        Assert.Equal("G_X", TranslateExpr("(float)x", "double x;"));
    }

    [Fact]
    public void Translate_Cast_BoolToInt_Unsupported()
    {
        // ManiaScript has no ternary and no boolean-to-number function — no expression form exists.
        Assert.Equal("/* cast from Boolean to Integer (ManiaScript has no boolean-to-number conversion; extract to an if/else assigning 1/0 explicitly) */", TranslateExpr("(int)x", "bool x;"));
    }

    [Fact]
    public void Translate_Cast_IntToBool_ComparesNotEqualZero()
    {
        Assert.Equal("(G_X != 0)", TranslateExpr("(bool)x", "int x;"));
    }

    [Fact]
    public void Translate_Cast_StringToInt_UsesTextLibToInteger()
    {
        Assert.Equal("TextLib::ToInteger(G_X)", TranslateExpr("(int)x", "string x;"));
    }

    [Fact]
    public void Translate_Cast_StringToFloat_UsesTextLibToReal()
    {
        Assert.Equal("TextLib::ToReal(G_X)", TranslateExpr("(float)x", "string x;"));
    }

    [Fact]
    public void Translate_Cast_IntToString_UsesTextLibToText()
    {
        Assert.Equal("TextLib::ToText(G_X)", TranslateExpr("(string)x", "int x;"));
    }

    [Fact]
    public void Translate_Cast_StringToBool_ComparesToTrueLiteral()
    {
        Assert.Equal("(G_X == \"True\")", TranslateExpr("(bool)x", "string x;"));
    }

    // ────────── Convert.To* methods ──────────

    [Fact]
    public void Translate_ConvertToInt32_FromFloat_UsesMathLibNearestInteger()
    {
        // Convert.ToInt32 rounds (unlike an explicit cast, which truncates).
        Assert.Equal("MathLib::NearestInteger(G_X)", TranslateExpr("Convert.ToInt32(x)", "float x;"));
    }

    [Fact]
    public void Translate_ConvertToInt32_FromString_UsesTextLibToInteger()
    {
        Assert.Equal("TextLib::ToInteger(G_X)", TranslateExpr("Convert.ToInt32(x)", "string x;"));
    }

    [Fact]
    public void Translate_ConvertToDouble_FromInt_UsesMathLibToReal()
    {
        Assert.Equal("MathLib::ToReal(G_X)", TranslateExpr("Convert.ToDouble(x)", "int x;"));
    }

    [Fact]
    public void Translate_ConvertToString_FromBool_UsesTextLibToText()
    {
        Assert.Equal("TextLib::ToText(G_X)", TranslateExpr("Convert.ToString(x)", "bool x;"));
    }

    [Fact]
    public void Translate_ConvertToInt32_FromBool_Unsupported()
    {
        Assert.Equal("/* Convert.ToInt32 from Boolean (ManiaScript has no boolean-to-number conversion; extract to an if/else assigning 1/0 explicitly) */", TranslateExpr("Convert.ToInt32(x)", "bool x;"));
    }

    [Fact]
    public void Translate_ConvertToBoolean_FromInt_ComparesNotEqualZero()
    {
        Assert.Equal("(G_X != 0)", TranslateExpr("Convert.ToBoolean(x)", "int x;"));
    }

    [Fact]
    public void Translate_ConvertToInt32_FromInt_IsNoOp()
    {
        Assert.Equal("G_X", TranslateExpr("Convert.ToInt32(x)", "int x;"));
    }

    // ────────── Instance .ToString() ──────────

    [Fact]
    public void Translate_ToString_OnNumeric_UsesConcatWithEmptyString()
    {
        Assert.Equal("\"\" ^ G_X", TranslateExpr("x.ToString()", "int x;"));
    }

    [Fact]
    public void Translate_ToString_OnIdent_UsesConcatWithEmptyString()
    {
        Assert.Equal("\"\" ^ G_X", TranslateExpr("x.ToString()", "public struct Ident {} Ident x;"));
    }

    [Fact]
    public void Translate_ToString_OnVec2_UsesConcatWithEmptyString()
    {
        Assert.Equal("\"\" ^ G_X", TranslateExpr("x.ToString()", "public struct Vec2 {} Vec2 x;"));
    }

    [Fact]
    public void Translate_ToString_OnVec3_UsesConcatWithEmptyString()
    {
        Assert.Equal("\"\" ^ G_X", TranslateExpr("x.ToString()", "public struct Vec3 {} Vec3 x;"));
    }

    [Fact]
    public void Translate_ToString_OnInt3_UsesConcatWithEmptyString()
    {
        Assert.Equal("\"\" ^ G_X", TranslateExpr("x.ToString()", "public struct Int3 {} Int3 x;"));
    }

    [Fact]
    public void Translate_ToString_OnClassReference_UsesConcatWithEmptyString()
    {
        // Any ManiaScript type — including class references — auto-converts via `^`.
        var (output, diagnostics) = TranslateExprWithDiagnostics("x.ToString()", "public class CFoo {} CFoo x = new CFoo();");
        Assert.Equal("\"\" ^ G_X", output);
        Assert.Empty(diagnostics);
    }

    // ────────── Dictionary methods ──────────

    [Fact]
    public void Translate_DictionaryContainsValue_MapsToExists()
    {
        Assert.Equal("G_Map.exists(5)", TranslateExpr("map.ContainsValue(5)", "Dictionary<string, int> map = new();"));
    }

    [Fact]
    public void Translate_DictionaryContainsKey_MapsToExistsKey()
    {
        Assert.Equal("G_Map.existskey(\"a\")", TranslateExpr("map.ContainsKey(\"a\")", "Dictionary<string, int> map = new();"));
    }

    [Theory]
    [InlineData("List<List<int>> items; List<int> item;")]
    [InlineData("List<int[]> items; int[] item;")]
    [InlineData("List<Dictionary<string, int>> items; Dictionary<string, int> item;")]
    [InlineData("struct Item { public int Value; } List<Item> items; Item item;")]
    public void Translate_ListContains_CompositeValueReportsError(string members)
    {
        var (output, diagnostics) = TranslateExprWithDiagnostics("items.Contains(item)", members);

        Assert.Equal("/* Contains(value) cannot check list or struct values */", output);
        Assert.Single(diagnostics);
        Assert.Equal("MSS022", diagnostics[0].Id);
        Assert.Equal(Microsoft.CodeAnalysis.DiagnosticSeverity.Error, diagnostics[0].Severity);
    }

    [Theory]
    [InlineData("Dictionary<string, List<int>> map; List<int> item;")]
    [InlineData("struct Item { public int Value; } Dictionary<string, Item> map; Item item;")]
    public void Translate_DictionaryContainsValue_CompositeValueReportsError(string members)
    {
        var (output, diagnostics) = TranslateExprWithDiagnostics("map.ContainsValue(item)", members);

        Assert.Equal("/* Contains(value) cannot check list or struct values */", output);
        Assert.Single(diagnostics);
        Assert.Equal("MSS022", diagnostics[0].Id);
        Assert.Equal(Microsoft.CodeAnalysis.DiagnosticSeverity.Error, diagnostics[0].Severity);
    }

    [Fact]
    public void Translate_ListContains_PrimitiveValueStillMapsToExists()
    {
        var (output, diagnostics) = TranslateExprWithDiagnostics("items.Contains(1)", "List<int> items;");

        Assert.Equal("G_Items.exists(1)", output);
        Assert.Empty(diagnostics);
    }

    [Theory]
    [InlineData("Ident")]
    [InlineData("Vec2")]
    [InlineData("Vec3")]
    [InlineData("Int2")]
    [InlineData("Int3")]
    public void Translate_ListContains_NativeScalarStructStillMapsToExists(string typeName)
    {
        // These stubs use the names that TypeMapper maps to native ManiaScript scalar types.
        var (output, diagnostics) = TranslateExprWithDiagnostics("items.Contains(item)",
            $"struct {typeName} {{ }} List<{typeName}> items; {typeName} item;");

        Assert.Equal("G_Items.exists(G_Item)", output);
        Assert.Empty(diagnostics);
    }

    [Fact]
    public void Translate_DictionaryContainsValue_IdentStillMapsToExists()
    {
        var (output, diagnostics) = TranslateExprWithDiagnostics("map.ContainsValue(item)",
            "struct Ident { } Dictionary<string, Ident> map; Ident item;");

        Assert.Equal("G_Map.exists(G_Item)", output);
        Assert.Empty(diagnostics);
    }

    [Fact]
    public void Translate_DictionaryContainsKey_CompositeKeyStillMapsToExistsKey()
    {
        var (output, diagnostics) = TranslateExprWithDiagnostics("map.ContainsKey(item)",
            "struct Item { public int Value; } Dictionary<Item, int> map; Item item;");

        Assert.Equal("G_Map.existskey(G_Item)", output);
        Assert.Empty(diagnostics);
    }

    [Fact]
    public void Translate_DictionaryCount_MapsToCount()
    {
        Assert.Equal("G_Map.count", TranslateExpr("map.Count", "Dictionary<string, int> map = new();"));
    }

    [Fact]
    public void Translate_DictionaryRemove_MapsToRemoveKey()
    {
        Assert.Equal("G_Map.removekey(\"a\")", TranslateExpr("map.Remove(\"a\")", "Dictionary<string, int> map = new();"));
    }

    [Theory]
    [InlineData("List<List<int>> items; List<int> item;")]
    [InlineData("List<int[]> items; int[] item;")]
    [InlineData("List<Dictionary<string, int>> items; Dictionary<string, int> item;")]
    [InlineData("struct Item { public int Value; } List<Item> items; Item item;")]
    public void Translate_ListRemove_CompositeValueReportsError(string members)
    {
        var (output, diagnostics) = TranslateExprWithDiagnostics("items.Remove(item)", members);

        Assert.Equal("/* List.Remove(value) cannot remove list or struct values */", output);
        Assert.Single(diagnostics);
        Assert.Equal("MSS021", diagnostics[0].Id);
        Assert.Equal(Microsoft.CodeAnalysis.DiagnosticSeverity.Error, diagnostics[0].Severity);
    }

    [Fact]
    public void Translate_ListRemove_PrimitiveValueStillMapsToRemove()
    {
        var (output, diagnostics) = TranslateExprWithDiagnostics("items.Remove(1)", "List<int> items;");

        Assert.Equal("G_Items.remove(1)", output);
        Assert.Empty(diagnostics);
    }

    [Theory]
    [InlineData("Ident")]
    [InlineData("Vec2")]
    [InlineData("Vec3")]
    [InlineData("Int2")]
    [InlineData("Int3")]
    public void Translate_ListRemove_NativeScalarStructStillMapsToRemove(string typeName)
    {
        var (output, diagnostics) = TranslateExprWithDiagnostics("items.Remove(item)",
            $"struct {typeName} {{ }} List<{typeName}> items; {typeName} item;");

        Assert.Equal("G_Items.remove(G_Item)", output);
        Assert.Empty(diagnostics);
    }

    [Fact]
    public void Translate_ListRemove_ClassReferenceStillMapsToRemove()
    {
        var (output, diagnostics) = TranslateExprWithDiagnostics("items.Remove(item)",
            "class CItem { } List<CItem> items; CItem item;");

        Assert.Equal("G_Items.remove(G_Item)", output);
        Assert.Empty(diagnostics);
    }

    [Fact]
    public void Translate_ListRemove_NullablePrimitiveStillMapsToRemove()
    {
        var (output, diagnostics) = TranslateExprWithDiagnostics("items.Remove(1)", "List<int?> items;");

        Assert.Equal("G_Items.remove(1)", output);
        Assert.Empty(diagnostics);
    }

    [Fact]
    public void Translate_ListRemoveAt_StructValueStillMapsToRemoveKey()
    {
        var (output, diagnostics) = TranslateExprWithDiagnostics("items.RemoveAt(0)",
            "struct Item { public int Value; } List<Item> items;");

        Assert.Equal("G_Items.removekey(0)", output);
        Assert.Empty(diagnostics);
    }

    [Fact]
    public void Translate_DictionaryRemove_StructValueStillMapsToRemoveKey()
    {
        var (output, diagnostics) = TranslateExprWithDiagnostics("map.Remove(1)",
            "struct Item { public int Value; } Dictionary<int, Item> map;");

        Assert.Equal("G_Map.removekey(1)", output);
        Assert.Empty(diagnostics);
    }

    [Fact]
    public void Translate_DictionaryGetValueOrDefault_MapsToGet()
    {
        Assert.Equal("G_Map.get(\"a\", 0)", TranslateExpr("map.GetValueOrDefault(\"a\", 0)", "Dictionary<string, int> map = new();"));
    }

    [Fact]
    public void Translate_TernaryExpression_UnsupportedInline()
    {
        // ManiaScript has no inline conditional; only the statement-level if/else
        // rewrite (StatementEmitter) can express `?:`. Used mid-expression it's unsupported.
        Assert.Equal("/* ternary operator '?:' (extract to an if/else statement) */", TranslateExpr("x > 0 ? 1 : -1", "int x;"));
    }

    [Fact]
    public void Translate_NullCoalescingAssignment_UnsupportedInline()
    {
        // ManiaScript has no `??=`; only supported as a top-level statement (StatementEmitter).
        Assert.Equal("/* '??=' (only supported as a top-level statement) */", TranslateExpr("x ??= 1", "object x;"));
    }

    // ────────── Collection expressions ──────────

    [Fact]
    public void Translate_CollectionExpression_IntList()
    {
        Assert.Equal("[1, 2, 3]", TranslateExpr("[1, 2, 3]"));
    }

    [Fact]
    public void Translate_EmptyCollectionExpression()
    {
        // [1, 2, 3] collection expression with elements works (tested separately);
        // [1, 2, 3] → "[1, 2, 3]"
        Assert.Equal("[1, 2, 3]", TranslateExpr("[1, 2, 3]"));
    }

    [Fact]
    public void Translate_NewList_EmptyLiteral()
    {
        // new List<T>() with collection initialiser → "[]"
        Assert.Equal("[1, 2]", TranslateExpr("new System.Collections.Generic.List<int> { 1, 2 }"));
    }

    [Fact]
    public void Translate_StructObjectInitializer_UsesNamedFields()
    {
        var output = TranslateExpr(
            "new MyStruct { MyMember = 1, MyTextMember = \"ready\" }",
            "struct MyStruct { public int MyMember; public string MyTextMember; }");

        Assert.Equal("MyStruct { MyMember = 1, MyTextMember = \"ready\" }", output);
    }

    [Fact]
    public void Translate_EmptyStructObjectInitializer_UsesEmptyStructLiteral()
    {
        var output = TranslateExpr("new MyStruct { }", "struct MyStruct { public int MyMember; }");

        Assert.Equal("MyStruct {}", output);
    }

    [Theory]
    [InlineData("CamelCase", "totalScore")]
    [InlineData("SnakeCase", "total_score")]
    public void Translate_StructFieldNaming_UsesConfiguredNamesInInitializersAndAccess(string style, string expectedName)
    {
        var members =
            "[ManiaScriptSharp.StructFieldNaming(ManiaScriptSharp.StructFieldNameStyle." + style + ")]\n" +
            "struct State { public int TotalScore; }\n" +
            "State state;";

        Assert.Equal($"State {{ {expectedName} = 1 }}", TranslateExpr("new State { TotalScore = 1 }", members));
        Assert.Equal($"G_State.{expectedName}", TranslateExpr("state.TotalScore", members));
    }

    [Fact]
    public void Translate_StructFieldJsonPropertyName_OverridesStructNaming()
    {
        const string members = """
            [ManiaScriptSharp.StructFieldNaming(ManiaScriptSharp.StructFieldNameStyle.SnakeCase)]
            struct State
            {
                [System.Text.Json.Serialization.JsonPropertyName("score")]
                public int TotalScore;
            }
            State state;
            """;

        Assert.Equal("State { score = 1 }", TranslateExpr("new State { TotalScore = 1 }", members));
        Assert.Equal("G_State.score", TranslateExpr("state.TotalScore", members));
    }

    [Fact]
    public void Translate_Int2Construction_UsesVectorLiteral()
    {
        var output = TranslateExpr("new Int2(0, 10)", "struct Int2 { public Int2(int x, int y) { } }");

        Assert.Equal("<0, 10>", output);
    }

    // ────────── Interpolated strings ──────────

    [Fact]
    public void Translate_InterpolatedString_Regular_ConcatenatesWithCaret()
    {
        // $"Hello {name}" → "Hello " ^ Name
        Assert.Equal("\"Hello \" ^ G_Name", TranslateExpr("$\"Hello {name}\"", "string name;"));
    }

    [Fact]
    public void Translate_InterpolatedString_Regular_PlainText()
    {
        // $"world" (no interpolations) → "world"
        Assert.Equal("\"world\"", TranslateExpr("$\"world\""));
    }

    [Fact]
    public void Translate_InterpolatedString_Regular_MultipleInterpolations()
    {
        // $"{a} and {b}" → A ^ " and " ^ B
        Assert.Equal("G_A ^ \" and \" ^ G_B", TranslateExpr("$\"{a} and {b}\"", "string a; string b;"));
    }

    [Fact]
    public void Translate_InterpolatedString_Regular_OnlyInterpolation()
    {
        // $"{name}" → Name (no surrounding quotes needed)
        Assert.Equal("G_Name", TranslateExpr("$\"{name}\"", "string name;"));
    }

    [Fact]
    public void Translate_InterpolatedString_Raw_TripleQuotedWithBraces()
    {
        // $"""Hello {name}""" → """Hello {{{Name}}}"""
        Assert.Equal("\"\"\"Hello {{{G_Name}}}\"\"\"", TranslateExpr("$\"\"\"Hello {name}\"\"\"", "string name;"));
    }

    [Fact]
    public void Translate_InterpolatedString_Raw_PlainText()
    {
        // $"""world""" → """world"""
        Assert.Equal("\"\"\"world\"\"\"", TranslateExpr("$\"\"\"world\"\"\""));
    }

    [Fact]
    public void Translate_InterpolatedString_Raw_LeadingWhitespaceStripped()
    {
        // Raw string literals strip the common leading indentation (ValueText vs Text).
        // The indented form: the compiler strips the indent to just the content.
        // We pass the expression directly so the raw string has no extra indent here.
        Assert.Equal("\"\"\"Hello\"\"\"", TranslateExpr("$\"\"\"Hello\"\"\""));
    }

    // ────────── Element access ──────────

    [Fact]
    public void Translate_ElementAccess()
    {
        Assert.Equal("G_Arr[0]", TranslateExpr("arr[0]", "int[] arr;"));
    }

    [Fact]
    public void Translate_ElementAccess_VariableIndex()
    {
        Assert.Equal("G_Arr[G_I]", TranslateExpr("arr[i]", "int[] arr; int i;"));
    }

    // ────────── ManiaScript.Now ──────────

    [Fact]
    public void Translate_ManiaScriptNow_MapsToNow()
    {
        // ManiaScript.Now is a special-cased member
        Assert.Equal("Now", TranslateExpr("ManiaScript.Now"));
    }

    // ────────── Console.WriteLine ──────────

    [Fact]
    public void Translate_ConsoleWriteLine_MapsToLog()
    {
        Assert.Equal("log(42)", TranslateExpr("Console.WriteLine(42)"));
    }

    [Fact]
    public void Translate_ConsoleWrite_MapsToLog()
    {
        Assert.Equal("log(\"x\")", TranslateExpr("Console.Write(\"x\")"));
    }

    // ────────── ManiaScript.Assert / Debug.Assert ──────────

    [Fact]
    public void Translate_ManiaScriptAssert_NoMessage()
    {
        Assert.Equal("assert(False)", TranslateExpr("ManiaScript.Assert(false)"));
    }

    [Fact]
    public void Translate_ManiaScriptAssert_WithMessage()
    {
        Assert.Equal("assert(False, \"oops\")", TranslateExpr("ManiaScript.Assert(false, \"oops\")"));
    }

    [Fact]
    public void Translate_DebugAssert_NoMessage()
    {
        Assert.Equal("assert(False)", TranslateExpr("System.Diagnostics.Debug.Assert(false)"));
    }

    [Fact]
    public void Translate_DebugAssert_WithMessage()
    {
        Assert.Equal("assert(False, \"oops\")", TranslateExpr("System.Diagnostics.Debug.Assert(false, \"oops\")"));
    }

    // ────────── Identifier resolution ──────────

    [Fact]
    public void Translate_UnhandledExpressionKind_EmitsComment()
    {
        // Any expression node type not explicitly handled should produce a /* expr */ comment
        // so the generated output clearly marks the gap rather than silently inserting raw C# source.
        // SwitchExpressionSyntax (`x switch { ... }`) is not in the handled set.
        var result = TranslateExpr("x switch { _ => 0 }", "int x;");
        Assert.StartsWith("/*", result);
        Assert.EndsWith("*/", result);
    }

    [Fact]
    public void Translate_PrivateField_PascalCased()
    {
        // Private field `_count` → `Count`
        Assert.Equal("G_Count", TranslateExpr("_count", "int _count;"));
    }

    [Fact]
    public void Translate_PublicField_GPrefix()
    {
        // Public field `count` → `G_Count`
        Assert.Equal("G_Count", TranslateExpr("count", "public int count;"));
    }

    // ────────── StrongBox<T>.Value stripping ──────────

    [Fact]
    public void Translate_StrongBoxValue_Read_StripsValue()
    {
        // myVar.Value (read) on a StrongBox<int> local → just myVar name in ManiaScript
        var extra = "System.Runtime.CompilerServices.StrongBox<int> myVar;";
        Assert.Equal("G_MyVar", TranslateExpr("myVar.Value", extra));
    }

    [Fact]
    public void Translate_StrongBoxValue_Write_StripsValue()
    {
        // myVar.Value = 42 → MyVar = 42 in ManiaScript
        var extra = "System.Runtime.CompilerServices.StrongBox<int> myVar;";
        Assert.Equal("G_MyVar = 42", TranslateExpr("myVar.Value = 42", extra));
    }

    // ────────── IContext.Main()/Loop() direct-call restriction ──────────

    [Fact]
    public void Translate_DirectMainCall_ReportsDiagnostic()
    {
        var (output, diagnostics) = TranslateExprWithDiagnostics(
            "Main()",
            "public void Main() { } public void Loop() { }",
            ": IContext");
        Assert.Equal("Main()", output);
        Assert.Contains(diagnostics, d => d.Id == "MSS010");
    }

    [Fact]
    public void Translate_DirectLoopCall_ReportsDiagnostic()
    {
        var (output, diagnostics) = TranslateExprWithDiagnostics(
            "Loop()",
            "public void Main() { } public void Loop() { }",
            ": IContext");
        Assert.Equal("Loop()", output);
        Assert.Contains(diagnostics, d => d.Id == "MSS010");
    }

    [Fact]
    public void Translate_UnrelatedLoopMethodCall_NoDiagnostic()
    {
        // A method named "Loop" that does not implement IContext.Loop() is unrelated and allowed.
        var (output, diagnostics) = TranslateExprWithDiagnostics(
            "Loop()",
            "public void Loop() { }");
        Assert.Equal("Loop()", output);
        Assert.DoesNotContain(diagnostics, d => d.Id == "MSS010");
    }

    // ────────── User-defined enums ──────────

    [Fact]
    public void Translate_RenamedOfficialEnumAndProperty_UseOriginalManiaScriptNames()
    {
        const string members = """
            public class COfficial
            {
                [ManiaScriptSharp.ManiaScriptName("Type")]
                public enum EType { Ready }
                public EType Type { get; }
            }
            COfficial item;
            """;

        Assert.Equal("G_Item.Type", TranslateExpr("item.Type", members));
        Assert.Equal("COfficial::Type::Ready", TranslateExpr("COfficial.EType.Ready", members));
    }

    [Fact]
    public void Translate_EnumNestedInContextClass_UsesGeneratedConst()
    {
        var (output, _) = TranslateExprWithDiagnostics(
            "MyState.Running",
            "enum MyState { Idle, Running } public void Main() { } public void Loop() { }",
            ": IContext");
        Assert.Equal("C_MyState_Running", output);
    }

    [Fact]
    public void Translate_EnumNestedInOtherType_UsesGeneratedConst()
    {
        var output = TranslateExpr(
            "CFoo.Color.Red",
            "public class CFoo { public enum Color { Red, Green } }");
        Assert.Equal("C_Color_Red", output);
    }

    [Fact]
    public void Translate_UserEnumCasts_AreIntegerNoOps()
    {
        const string members = "enum State { Ready = 2 }";
        Assert.Equal("C_State_Ready", TranslateExpr("(int)State.Ready", members));
        Assert.Equal("2", TranslateExpr("(State)2", members));
    }

    [Fact]
    public void Translate_UserEnumDefaults_AreZero()
    {
        const string members = "enum State { Ready = 2 }";
        Assert.Equal("0", TranslateExpr("default(State)", members));
        Assert.Equal("declare Integer State = 0;", TranslateStmt("State state = default;", members));
    }
}

