<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <ManiaScriptOutputDir>ManiaScript</ManiaScriptOutputDir>
        <ManiaScriptIndentSize>2</ManiaScriptIndentSize>
        <ManiaScriptIndentStyle>spaces</ManiaScriptIndentStyle>
<!--#if (IsTrackmania) -->
        <ManiaScriptVersion>2</ManiaScriptVersion>
<!--#endif -->
    </PropertyGroup>

    <ItemGroup>
        <Using Include="ManiaScriptSharp" />
        <Using Static="true" Include="ManiaScriptSharp.ManiaScript" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ManiaScriptSharp" Version="*" />
        <PackageReference Include="ManiaScriptSharp.Generator" Version="*" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
<!--#if (IsManiaPlanet) -->
        <PackageReference Include="ManiaScriptSharp.ManiaPlanet" Version="*" />
<!--#endif -->
<!--#if (IsTrackmania) -->
        <PackageReference Include="ManiaScriptSharp.Trackmania" Version="*" />
<!--#endif -->
    </ItemGroup>

</Project>
