name: CI

on:
  push:
    paths: [ ".github/workflows/ci.yml", "src/**", "samples/**", "tests/**", "ManiaScriptSharp.slnx" ]
  workflow_dispatch:

jobs:
  ci:
    name: Continuous Integration
    uses: bigbang1112/workflows/.github/workflows/ci.yml@main
    with:
      dotnet-version: 10.0.x