# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Generate docs
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: Docs/docfx.json
          
      - name: Upload docs artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: docs
          path: Docs/_site
          retention-days: 1
