name: Publish NuGet

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: write # important for release creation and asset upload
  packages: write

jobs:
  deploy:
    name: Publish NuGet
    uses: bigbang1112/workflows/.github/workflows/publish-nuget-immutable.yml@main
    with:
      dotnet-version: 10.x.x
      project-path: src/*
      test-path: tests/*
      pack-path: "{src/*,templates/*}"
      release-title-prefix: ManiaScriptSharp
      main-project: ManiaScriptSharp
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}